# utils/scene_understanding.py
from utils.api_integration import gemini_api_request

def generate_scene_description(image_path: str) -> str:
    """
    Generates a descriptive scene understanding for an image using Gemini API.

    Args:
        image_path (str): Path to the image file.

    Returns:
        str: Scene description generated by the API.
    """
    endpoint = "scene-understanding"
    payload = {
        "image_path": image_path
    }
    
    response = gemini_api_request(endpoint, payload)
    if "description" in response:
        return response["description"]
    else:
        return "Error: Unable to generate description."
